somehow did not detected and abssetnt
```
Error: Could not find haxelib "flxanimate", does it need to be installed?
Error: Process completed with exit code 1.
```

upon inspection, some package were missing