separate CI
because there's trouble with Android.
```
Creating D:/a/Kaded-fnf-mods/Kaded-fnf-mods/export/release/android/obj/obj/android-v7/__pch/haxe/hxcpp.h.gch...
'arm-linux-androideabi-g++' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not create PCH
```