whoah
mac os cannot linc_clipboard

```
 - /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/project/thirdparty/pcre2-10.42/src/pcre2_extuni.c
 - /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/project/thirdparty/pcre2-10.42/src/pcre2_study.c
 - /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/project/thirdparty/pcre2-10.42/src/pcre2_tables.c
 - /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/project/thirdparty/pcre2-10.42/src/pcre2_config.c
 - /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/project/thirdparty/pcre2-10.42/src/pcre2_find_bracket.c
 - /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/project/thirdparty/pcre2-10.42/src/pcre2_maketables.c
 - /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/project/thirdparty/pcre2-10.42/src/pcre2_pattern_info.c

Compiling group: linc_clipboard
xcrun --sdk macosx13.1 clang++ -I/Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/linc_clipboard/git//linc/ -c -fvisibility=hidden -stdlib=libc++ -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -O2 -I/Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include -DHX_MACOS -arch x86_64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-overflow -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_TRACE(haxe) -DHXCPP_STACK_LINE(haxe) -DHXCPP_GC_BIG_BLOCKS(gc) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=430(haxe) ... tags=[haxe,static]
 - /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/linc_clipboard/git//linc/linc_clipboard_mac.mm
Error: In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/linc_clipboard/git//linc/linc_clipboard_mac.mm:7:
In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/linc_clipboard/git//linc/./linc_clipboard.h:4:
In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/hxcpp.h:357:
/Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/Dynamic.h:424:29: error: found '<::' after a template name which forms the digraph '<:' (aka '[') and a ':', did you mean '< ::'?
inline bool Dynamic::IsClass<::cpp::Int64>() { return mPtr && mPtr->__GetClass()==hx::GetInt64Class(); }
                            ^~~
                            < ::
In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/linc_clipboard/git//linc/linc_clipboard_mac.mm:7:
In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/linc_clipboard/git//linc/./linc_clipboard.h:4:
In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/hxcpp.h:362:
/Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/Array.h:47:29: error: found '<::' after a template name which forms the digraph '<:' (aka '[') and a ':', did you mean '< ::'?
template<> struct ReturnNull<::cpp::Int64> { typedef Dynamic type; };
                            ^~~
                            < ::
/Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/Array.h:56:30: error: found '<::' after a template name which forms the digraph '<:' (aka '[') and a ':', did you mean '< ::'?
template<> struct ArrayTraits<::cpp::Int64> { enum { StoreType = arrayInt64 }; };
                             ^~~
                             < ::
/Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/Array.h:464:40: error: found '<::' after a template name which forms the digraph '<:' (aka '[') and a ':', did you mean '< ::'?
template<> inline ::cpp::Int64 *NewNull<::cpp::Int64>() { ::cpp::Int64 i=0; return (::cpp::Int64 *)hx::NewGCPrivate(&i,sizeof(i)); }
                                       ^~~
                                       < ::
/Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/Array.h:481:31: error: found '<::' after a template name which forms the digraph '<:' (aka '[') and a ':', did you mean '< ::'?
template<> struct ArrayClassId<::cpp::Int64> { enum { id=hx::clsIdArrayInt64 }; };
                              ^~~
                              < ::
In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/linc_clipboard/git//linc/linc_clipboard_mac.mm:7:
In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/linc_clipboard/git//linc/./linc_clipboard.h:4:
In file included from /Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/hxcpp.h:364:
/Users/runner/work/Kaded-fnf-mods/Kaded-fnf-mods/.haxelib/hxcpp/4,3,2/include/hx/Class.h:36:26: error: found '<::' after a template name which forms the digraph '<:' (aka '[') and a ':', did you mean '< ::'?
inline hx::Class &ClassOf<::cpp::Int64>() { return GetInt64Class(); }
                         ^~~
                         < ::
6 errors generated.
Error: The operation was canceled.
```